"""Constants for the econet Integration integration."""

DOMAIN = "econet300"

API_PROP_NAME = "api"
COORDINATOR_PROP_NAME = "coordinator"

DEVICE_INFO_MANUFACTURER = "PLUM"
DEVICE_INFO_MODEL = "ecoNET300"
DEVICE_INFO_NAME = "PLUM ecoNET300"

CONF_ENTRY_TITLE = "ecoNET300"
CONF_ENTRY_DESCRIPTION = "PLUM Econet300"